The `.UHF` file is now written if the molecule has a uhf larger than 0
grimme-lab/MindlessGen pull request #74
Opened 2024-11-11 12:48 UTC by jonathan-schoeps

The `.UHF` file is now only written if the molecule has `uhf > 0`. This should make it more convenient to use `MindlessGen` together with `g-xTB`.

2024-11-13 08:18 UTC, jonathan-schoeps commented
But is this something that would make sense to do, or were these files necessary for something?

2024-11-13 08:33 UTC, marcelmbn commented
> But is this something that would make sense to do, or were these files necessary for something?

They are definitely helpful and necessary for the case that `.CHRG` and `.UHF` are not 0 (-> not [neutral + closed-shell]). If a molecule is neutral and doesn't have unpaired electrons, we can also not write the files. I'd say there is no right or wrong in this question, this is probably a question of personal preference.

2024-11-18 10:39 UTC, marcelmbn requested changes

2024-11-18 11:56 UTC, marcelmbn approved these changes

2024-11-18 11:56 UTC, merged